# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys,res
import os
from Database_methods import *
from main import *
class Ui_FormSign(object):
        
        
       
                
        
        def setupUi(self, FormSign):
                FormSign.setObjectName("FormSign")
                FormSign.resize(617, 460)
                FormSign.setWindowFlags(QtCore.Qt.FramelessWindowHint)
                FormSign.setAttribute(QtCore.Qt.WA_TranslucentBackground)
                icon = QtGui.QIcon(":/ressources/logo.png")
                FormSign.setWindowIcon(icon)
                self.widget = QtWidgets.QWidget(FormSign)
                self.widget.setGeometry(QtCore.QRect(0, -10, 551, 451))
                
                self.widget.setStyleSheet("QPushButton#loginBtn,#signBtn{\n"
        "background-color: qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(20,47,78,219),stop:1 rgba(85,98,112,226));\n"
        "\n"
        "color:rgba(255,255,255,210);\n"
        "\n"
        "border-radius: 5px\n"
        "}\n"
        "\n"
        "QPushButton#loginBtn:hover{\n"
        "background-color: qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(40,67,98,219),stop:1 rgba(105,118,132,226));\n"
        "\n"
        "color:rgba(255,255,255,210);\n"
        "\n"
        "border-radius: 5px\n"
        "}\n"
        "QPushButton#signBtn:hover{\n"
        "background-color: qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(40,67,98,219),stop:1 rgba(105,118,132,226));\n"
        "\n"
        "color:rgba(255,255,255,210);\n"
        "\n"
        "border-radius: 5px\n"
        "}\n"
        "\n"
        "QPushButton#loginBtn,#signBtn:pressed{\n"
        "padding-left: 5px;\n"
        "padding-top: 5px;\n"
        "background-color : rgba(105,118,132,200);\n"
        "}\n"
        "\n"
        "\n"
        "QPushButton#emailBtn:pressed{\n"
        "padding-left: 5px;\n"
        "padding-top: 5px;\n"
        "background-color : rgba(105,118,132,200);\n"
        "}\n"
        "QPushButton#callBtn:pressed{\n"
        "padding-left: 5px;\n"
        "padding-top: 5px;\n"
        "background-color : rgba(105,118,132,200);\n"
        "}")
                self.widget.setObjectName("widget")
                self.label = QtWidgets.QLabel(self.widget)
                self.label.setGeometry(QtCore.QRect(30, 19, 511, 431))
                self.label.setStyleSheet("border-image: url(:/ressources/bg.jpg);\n"
        "border-radius : 20px;")
                self.label.setText("")
                self.label.setObjectName("label")
                self.label_2 = QtWidgets.QLabel(self.widget)
                self.label_2.setGeometry(QtCore.QRect(30, 19, 511, 431))
                self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:0.715909,stop:0.375 rgba(0,0,0,50),stop:0.835227 rgba(0,0,0,75));\n"
        "border-radius : 20px;")
                self.label_2.setText("")
                self.label_2.setObjectName("label_2")
                self.label_3 = QtWidgets.QLabel(self.widget)
                self.label_3.setGeometry(QtCore.QRect(40, 29, 491, 411))
                self.label_3.setStyleSheet("background-color: rgba(0,0,0,100);\n"
        "border-radius : 15px;")
                self.label_3.setText("")
                self.label_3.setObjectName("label_3")
                self.label_4 = QtWidgets.QLabel(self.widget)
                self.label_4.setGeometry(QtCore.QRect(50, 30, 51, 51))
                font = QtGui.QFont()
                font.setPointSize(20)
                font.setBold(True)
                font.setWeight(75)
                self.label_4.setFont(font)
                self.label_4.setStyleSheet("color: rgba(255,255,255,210);")
                self.label_4.setText("")
                self.label_4.setPixmap(QtGui.QPixmap(":/images/logo.png"))
                self.label_4.setScaledContents(True)
                self.label_4.setObjectName("label_4")
                self.usernameEdit = QtWidgets.QLineEdit(self.widget)
                self.usernameEdit.setGeometry(QtCore.QRect(290, 160, 200, 40))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.usernameEdit.setFont(font)
                self.usernameEdit.setStyleSheet("background: rgba(0,0,0,0);\n"
        "border:0;\n"
        "border-bottom:2px solid rgba(105,118,132,255);\n"
        "color:rgba(255,255,255,230);\n"
        "padding-bottom:7px")
                self.usernameEdit.setObjectName("usernameEdit")
                self.passwordEdit = QtWidgets.QLineEdit(self.widget)
                self.passwordEdit.setGeometry(QtCore.QRect(290, 210, 200, 40))
                font = QtGui.QFont()
                font.setFamily("MS Shell Dlg 2")
                font.setPointSize(10)
                self.passwordEdit.setFont(font)
                self.passwordEdit.setStyleSheet("background: rgba(0,0,0,0);\n"
        "border:0;\n"
        "border-bottom:2px solid rgba(105,118,132,255);\n"
        "color:rgba(255,255,255,230);\n"
        "padding-bottom:7px")
                self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
                self.passwordEdit.setObjectName("passwordEdit")
                self.signBtn = QtWidgets.QPushButton(self.widget)
                self.signBtn.setGeometry(QtCore.QRect(160, 380, 241, 40))
                font = QtGui.QFont()
                font.setPointSize(12)
                font.setBold(True)
                font.setWeight(75)
                self.signBtn.setFont(font)
                self.signBtn.setObjectName("signBtn")
                self.label_5 = QtWidgets.QLabel(self.widget)
                self.label_5.setGeometry(QtCore.QRect(110, 50, 101, 21))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_5.setFont(font)
                self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
                self.label_5.setObjectName("label_5")
                self.gradeEdit = QtWidgets.QLineEdit(self.widget)
                self.gradeEdit.setGeometry(QtCore.QRect(50, 300, 200, 40))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.gradeEdit.setFont(font)
                self.gradeEdit.setStyleSheet("background: rgba(0,0,0,0);\n"
        "border:0;\n"
        "border-bottom:2px solid rgba(105,118,132,255);\n"
        "color:rgba(255,255,255,230);\n"
        "padding-bottom:7px")
                self.gradeEdit.setObjectName("gradeEdit")
                self.hospitalEdit = QtWidgets.QLineEdit(self.widget)
                self.hospitalEdit.setGeometry(QtCore.QRect(50, 260, 200, 40))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.hospitalEdit.setFont(font)
                self.hospitalEdit.setStyleSheet("background: rgba(0,0,0,0);\n"
        "border:0;\n"
        "border-bottom:2px solid rgba(105,118,132,255);\n"
        "color:rgba(255,255,255,230);\n"
        "padding-bottom:7px")
                self.hospitalEdit.setObjectName("hospitalEdit")
                self.wilayaEdit = QtWidgets.QComboBox(self.widget)
                self.wilayaEdit.setGeometry(QtCore.QRect(50, 210, 200, 40))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.wilayaEdit.setFont(font)
                self.wilayaEdit.setStyleSheet("background: rgba(0,0,0,0);\n"
        "border:0;\n"
        "border-bottom:2px solid rgba(105,118,132,255);\n"
        "color:rgba(255,255,255,230);\n"
        "padding-bottom:7px")
                #self.wilayaEdit.setText("")
                #! Ajouter les noms des wilayas algériennes au ComboBox
                wilayas = [
                "Adrar", "Chlef", "Laghouat", "Oum El Bouaghi", "Batna", "Béjaïa",
                "Biskra", "Béchar", "Blida", "Bouira", "Tamanrasset", "Tébessa",
                "Tlemcen", "Tiaret", "Tizi Ouzou", "Alger", "Djelfa", "Jijel",
                "Sétif", "Saïda", "Skikda", "Sidi Bel Abbès", "Annaba", "Guelma",
                "Constantine", "Médéa", "Mostaganem", "M'Sila", "Mascara",
                "Ouargla", "Oran", "El Bayadh", "Illizi", "Bordj Bou Arreridj",
                "Boumerdès", "El Tarf", "Tindouf", "Tissemsilt", "El Oued",
                "Khenchela", "Souk Ahras", "Tipaza", "Mila", "Aïn Defla",
                "Naâma", "Aïn Témouchent", "Ghardaïa", "Relizane"
                ]
                self.wilayaEdit.addItems(wilayas)
                self.wilayaEdit.setObjectName("wilayaEdit")
                self.nameEdit = QtWidgets.QLineEdit(self.widget)
                self.nameEdit.setGeometry(QtCore.QRect(50, 110, 200, 40))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.nameEdit.setFont(font)
                self.nameEdit.setStyleSheet("background: rgba(0,0,0,0);\n"
        "border:0;\n"
        "border-bottom:2px solid rgba(105,118,132,255);\n"
        "color:rgba(255,255,255,230);\n"
        "padding-bottom:7px")
                self.nameEdit.setText("")
                self.nameEdit.setObjectName("nameEdit")
                self.nameEdit_2 = QtWidgets.QDateEdit(self.widget)
                self.nameEdit_2.setGeometry(QtCore.QRect(50, 160, 200, 40))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.nameEdit_2.setFont(font)
                self.nameEdit_2.setStyleSheet("background: rgba(0,0,0,0);\n"
        "border:0;\n"
        "border-bottom:2px solid rgba(105,118,132,255);\n"
        "color:rgba(255,255,255,230);\n"
        "padding-bottom:7px")
                
                self.nameEdit_2.setObjectName("nameEdit_2")
                self.label_7 = QtWidgets.QLabel(self.widget)
                self.label_7.setGeometry(QtCore.QRect(170, 80, 231, 31))
                font = QtGui.QFont()
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.label_7.setFont(font)
                self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
                self.label_7.setObjectName("label_7")
                self.passwordEdit_2 = QtWidgets.QLineEdit(self.widget)
                self.passwordEdit_2.setGeometry(QtCore.QRect(290, 260, 200, 40))
                font = QtGui.QFont()
                font.setFamily("MS Shell Dlg 2")
                font.setPointSize(10)
                self.passwordEdit_2.setFont(font)
                self.passwordEdit_2.setStyleSheet("background: rgba(0,0,0,0);\n"
        "border:0;\n"
        "border-bottom:2px solid rgba(105,118,132,255);\n"
        "color:rgba(255,255,255,230);\n"
        "padding-bottom:7px")
                self.passwordEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
                self.passwordEdit_2.setObjectName("passwordEdit_2")
                self.label.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius = 25 , xOffset=0 , yOffset = 0,color = QtGui.QColor(234,221,186,100)))

                self.msg = QtWidgets.QMessageBox()
                self.msg.setWindowTitle("Information")
                self.msg.setWindowIcon(QtGui.QIcon(":/ressources/logo.png"))
                
                self.retranslateUi(FormSign)
                QtCore.QMetaObject.connectSlotsByName(FormSign)
                self.signBtn.clicked.connect(self.ClinicianSignUp)
                
        def close_window(self):
                self.window.close()
        def retranslateUi(self, FormSign):
                _translate = QtCore.QCoreApplication.translate
                FormSign.setWindowTitle(_translate("FormSign", "Form"))
                self.usernameEdit.setPlaceholderText(_translate("FormSign", "User Name"))
                self.passwordEdit.setPlaceholderText(_translate("FormSign", "Password"))
                self.signBtn.setText(_translate("FormSign", "Sign  Up"))
                self.label_5.setText(_translate("FormSign", "Easy Nodule"))
                self.gradeEdit.setPlaceholderText(_translate("FormSign", "Grade"))
                self.hospitalEdit.setPlaceholderText(_translate("FormSign", "Hospital"))
                self.wilayaEdit.setPlaceholderText(_translate("FormSign", "Wilaya"))
                self.nameEdit.setPlaceholderText(_translate("FormSign", "Name"))
                #self.nameEdit_2.setPlaceholderText(_translate("FormSign", "Birthday DD/MM/YYYY"))
                self.label_7.setText(_translate("FormSign", "Enter Your Information"))
                self.passwordEdit_2.setPlaceholderText(_translate("FormSign", "Confirm Password"))
        def openWindow2(self):
                from login import Ui_Form
                self.window = QtWidgets.QWidget()
                self.ui = Ui_Form()
                self.ui.setupUi(self.window)
                self.window.show()
        def ClinicianSignUp(self):
                wilaya_selected = self.wilayaEdit.itemText(self.wilayaEdit.currentIndex())
                print(wilaya_selected)
                #! Verify if all the fields are filled
                if self.nameEdit.text()=="" or self.nameEdit_2.text()=="" or self.hospitalEdit.text()=="" or self.gradeEdit.text()=="" or self.usernameEdit.text()=="" or self.passwordEdit.text()=="" or self.passwordEdit_2.text()=="":
                        self.msg.setText("Please fill all the fields")
                        self.msg.exec_()
                elif ClinicianResearch(self.usernameEdit.text())== -1:
                        if self.passwordEdit.text() == self.passwordEdit_2.text():
                                ClinicianInsert(self.nameEdit.text(), self.nameEdit_2.text(), wilaya_selected, 
                                                self.hospitalEdit.text(), self.gradeEdit.text(), 
                                                self.passwordEdit.text(), self.usernameEdit.text()
                                                )
                                self.msg.setText("Your are account has been created")
                                self.msg.exec_()
                                wilaya_selected = "Adrar"
                                self.wilayaEdit.setCurrentIndex(0)
                                self.passwordEdit.clear()
                                self.passwordEdit_2.clear()
                                self.gradeEdit.clear()
                                self.hospitalEdit.clear()
                                self.usernameEdit.clear()
                                self.nameEdit.clear()
                                self.nameEdit_2.setDate(QDate(2000, 1, 1))
                                
                                
                                
                                
                        
                        else:
                                self.msg.setText("The password is incorrect, please check your password again")
                                self.msg.exec_()
                else:
                        self.msg.setText("Choose another username, it's already tooken")
                        self.msg.exec_()
                        
                    
                        

                
    
